### ISSUE TITLE
Embedded album art not displaying

### ISSUE THREAD

**Issue by natn4y** [swingmx/swingmusic#313]
I’ve tried several tools to embed album art into MP3 files, and it works well in other audio players. However, in SwingMusic, the embedded images don’t appear. I’ve also tried using Picard and changing the tag versions from 2.3 to 2.4, but nothing seems to work. The music files were downloaded using yt-dlp.

I’m using the latest version with Docker, and I’ve also tried running it outside Docker, but the issue persists.

**Comment by az2oo1** [comment]
same here but with music files

**Comment by cwilvx** [comment]
Hello guys

I'm finally able to reproduce this bug and I'm working to fix it asap.

@az2oo1 @MolassesLover @natn4y @Coding-Kiwi @Ahmed-Yazdan-2004

**Comment by cwilvx** [comment]
Hello @MolassesLover 

I'm not sure what's going on there, so I've created a beta release for you which you can pull via Docker:

https://github.com/swingmx/swingmusic/pkgs/container/swingmusic/440679947?tag=v2.0.8.beta1

**Comment by Coding-Kiwi** [comment]
I tried the beta tag in docker

![Image](https://github.com/user-attachments/assets/81531183-494c-4166-b933-e387538fc994)

(SWINGMUSIC_APP_VERSION is still 2.0.7)

![Image](https://github.com/user-attachments/assets/ecc65260-bff7-4649-9ea2-b58460f61e9f)

sadly this did not bring back the art

**Comment by cwilvx** [comment]
Hello @MolassesLover 

I think the albums showing images are the ones with a `cover.jpg` somewhere.

I think I actually fixed the bug (for real this time guys ... hopefully). It had something to do with multiprocessing. You can check out [the fix commit](https://github.com/swingmx/swingmusic/commit/4788295b975374003612ed3345c3d52bc0ad1ed7).

I also [rewrote color extraction](https://github.com/swingmx/swingmusic/commit/64fe9148204c7534cb12e70786dbb7d2eae52a5d) with _wait for it_ .... multiprocessing. I hope that won't introduce new bugs.

I have also released `v2.0.8` which contains the fix. You can view the release notes here:


Docker: https://github.com/orgs/swingmx/packages/container/swingmusic/441760395?tag=v2.0.8

Release page: https://github.com/swingmx/swingmusic/releases/tag/v2.0.8

Enjoy guys

**Comment by cwilvx** [comment]
Hello @Coding-Kiwi 

I think that's not a bug, rather than a library issue. Swing Music assigns the same thumbnails to tracks belonging to the same album. If your music files are not tagged properly, have missing album names, or have a generic album name, that could result in the behavior indicated in your screenshots.

Please update your file tags using a tag editor, then rescan your library in Swing Music.

Thanks.

**Comment by Kevinwg02** [comment]
I just updated my docker compose file and I still have the issue. Is there a specific version to install ? 

<img width="1238" height="750" alt="Image" src="https://github.com/user-attachments/assets/5dcd4240-4b91-4180-8cb8-b57a68966aae" />

name: swingmusic
services:
    swingmusic:
        cpu_shares: 90
        command: []
        container_name: swingmusic
        deploy:
            resources:
                limits:
                    memory: "33533460480"
        hostname: swingmusic
        image: ghcr.io/swingmx/swingmusic:latest
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/icon.png
        networks:
            default: null
        ports:
            - mode: ingress
              target: *
              published: "*"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/swingmusic/config
              target: /config
            - type: bind
              source: /vault/mediavault/Musique
              target: /music
networks:
    default:
        name: swingmusic_default
